/* 由 src/b2-worker.js 拆分而来：原 L2403-L3213 */

import { API_PREFIX, MANAGE_PATH } from '../lib/constants.js';
import { inlineJson, themeCss, themeToggleScript } from './theme.js';

export function managePage(cfg, url) {
  // 管理器挂在挂载点下：/<bucket>/__manage 或别名 /share/<bucket>/__manage
  const basePath = url.pathname.slice(0, -MANAGE_PATH.length) || '/';
  const apiBase = basePath.replace(/\/+$/, '') + API_PREFIX;
  const defaultBucket = cfg.bucketFixed;

  // 对象访问根路径（挂载点前缀），下载一律走这里，不再用预签名直链
  const objectBase = basePath.endsWith('/') ? basePath : basePath + '/';

  // 「退出」后的去向：公开目录根（默认 /share/）；未配置公开前缀时退回站点根 /
  const publicHome = '/' + String(cfg.publicPrefix || '').replace(/^\/+|\/+$/g, '') + '/';
  const exitUrl = cfg.publicPrefix ? publicHome : '/';

  const configJson = inlineJson({
    apiBase,
    basePath: objectBase,
    exitUrl,
    defaultBucket,
    bucket: cfg.bucketFixed,
    buckets: cfg.buckets.map((b) => ({ name: b.name, label: b.label })),
    publicPrefix: cfg.publicPrefix,
    bucketMode: cfg.bucketMode,
    bucketFixed: cfg.bucketFixed,
    hasToken: Boolean(cfg.adminToken),
    hasBasic: Boolean(cfg.adminUser || cfg.adminPass),
    publicWrite: cfg.publicWrite,
    enableWrite: cfg.enableWrite,
    enableDelete: cfg.enableDelete,
    multipartThreshold: cfg.multipartThreshold,
    multipartPartSize: cfg.multipartPartSize,
    maxUploadBytes: cfg.maxUploadBytes,
    uploadConcurrency: cfg.uploadConcurrency,
    apiPrefix: API_PREFIX,
  });

  // 上传调参输入框的默认值（MiB / 并发数），取服务端配置
  const defaultPartMiB = Math.max(5, Math.min(Math.round((cfg.multipartPartSize || 0) / 1048576) || 25, 95));
  const defaultConc = Math.max(1, Math.min(10, cfg.uploadConcurrency || 3));

  return [
    '<!doctype html>',
    '<html lang="zh-CN"><head><meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>B2 文件管理器</title>',
    // 空 favicon：避免浏览器自动请求 /favicon.ico（会被当对象下载，白记 1 次 Class B）
    '<link rel="icon" href="data:,">',
    '<style>',
    themeCss(),
    '*{box-sizing:border-box}',
    'body{margin:0;background:var(--bg);color:var(--txt);font-family:system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif;font-size:14px}',
    'code{background:var(--chip);padding:2px 6px;border-radius:5px}',
    'header{display:flex;align-items:center;gap:10px;padding:12px 20px;border-bottom:1px solid var(--line);background:var(--card);position:sticky;top:0;z-index:5;flex-wrap:wrap}',
    'header h1{font-size:15px;margin:0;font-weight:600}',
    '.grow{flex:1}',
    'button,input,select{font:inherit;color:var(--txt);background:var(--chip);border:1px solid var(--line);border-radius:8px;padding:6px 10px}',
    'button{cursor:pointer;background:var(--acc);border-color:var(--acc);color:var(--btn)}',
    'button.ghost{background:var(--chip);color:var(--txt);border-color:var(--line)}',
    'button.mini{padding:3px 7px;font-size:12px;background:var(--chip);border-color:var(--line);color:var(--txt)}',
    'button:disabled{opacity:.45;cursor:not-allowed}',
    // 桌面端：左侧用量卡片（360px，容纳多桶两列），右侧文件列表
    'main{max-width:1400px;margin:0 auto;padding:20px;display:grid;grid-template-columns:360px minmax(0,1fr);gap:20px;align-items:start}',
    '.content{min-width:0}',
    // 表格列宽用 class 而不用内联样式，移动端断点才能覆盖
    '.c-size{width:110px}.c-time{width:180px}.c-act{width:300px;text-align:right}.act{text-align:right}',
    // 移动端「更多」折叠区：桌面用 display:contents，子项直接参与 header 的 flex 布局
    // order 的取值刻意让桌面视觉顺序稳定（桶切换器在新建目录之前）
    '.more{display:contents}',
    '.more-toggle{display:none}',
    '.more>*{order:1}',
    '#bucketSel{order:2}',
    '#btnMkdir{order:3}#upMode{order:4}',
    '.more .set,.more #btnTheme{order:5}',
    '#btnUpload{order:6}',
    // 移动端：① 不显示 B2 桶信息 ② 顶部只常显「新建目录 / 上传方式 / 上传」，其余折叠
    // ③ 隐藏「修改时间」并拉宽「操作」，让「复制/下载/重命名/删除」放得下、好点
    '@media (max-width:860px){',
    'main{grid-template-columns:1fr;gap:14px}',
    '.side{display:none}',
    'header{padding:10px 12px;gap:8px}',
    '.more{display:none;order:9;width:100%;flex-wrap:wrap;gap:10px;align-items:center;margin-top:6px;padding-top:10px;border-top:1px solid var(--line)}',
    '.more.more-open{display:flex}',
    '.more>*{order:0}',
    '.more .grow{display:none}',
    '.more h1{font-size:14px}',
    '.more-toggle{display:inline-block;order:4}',
    '#btnMkdir{order:1}#upMode{order:2}#btnUpload{order:3}',
    // 桶切换器在移动端收进折叠区
    '#bucketSel{order:0;max-width:150px}',
    // 文件列表：文件行为「两行」（第一行 名称+大小，第二行 四个操作按钮整行铺开；
    // 390px 下按钮挤在名称右侧会让名称只剩 ~58px，长文件名折成 10 行）。
    // 目录行保持「一行」：名称占满、删除按钮尾部右对齐（目录只有一个按钮，放得下）。
    'table,tbody,tr,td{display:block}',
    'thead{display:none}',
    'table{border:0;background:transparent}',
    'tbody tr{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;padding:10px 4px;border-bottom:1px solid var(--line);background:var(--card)}',
    'tbody tr:last-child{border-bottom:0}',
    'tbody td{padding:0;border:0;overflow-wrap:anywhere}',
    'tbody td:empty{display:none}',
    'tbody td:nth-child(2){text-align:right;white-space:nowrap;color:var(--dim);font-size:12px;align-self:center}',
    'tbody td:nth-child(3){display:none}',
    'tbody td.act{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:8px;text-align:left}',
    'tbody td.act .mini{flex:1 1 72px;min-height:42px;padding:8px 6px;font-size:13px}',
    'tbody tr.dir{display:flex;align-items:center;gap:8px;background:var(--folder)}',
    'tbody tr.dir td:first-child{flex:1;min-width:0}',
    'tbody tr.dir td.act{display:block;text-align:right;flex:0 0 auto;grid-column:auto}',
    'tbody tr.dir td.act .mini{flex:0 0 auto;padding:8px 18px}',
    '}',
    '#status{margin-top:14px;font-size:12px;display:flex;align-items:center;gap:8px;justify-content:center}',
    '#status .spin{width:12px;height:12px;border:2px solid var(--line);border-top-color:var(--acc);border-radius:50%;animation:sp 0.8s linear infinite}',
    '@keyframes sp{to{transform:rotate(360deg)}}',
    'table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line);border-radius:12px;overflow:hidden}',
    'th,td{padding:8px 12px;border-bottom:1px solid var(--line);text-align:left}',
    'th{color:var(--dim);font-weight:500;font-size:12px;letter-spacing:.04em}',
    'tr:last-child td{border-bottom:0}tr:hover td{background:var(--hover)}',
    'tr.dir td{background:var(--folder)}tr.dir:hover td{background:var(--hover)}',
    'tr.dir td a{color:var(--folderTxt)}tr.dir td button{color:var(--folderTxt)}',
    '.muted{color:var(--dim)}',
    '.bar{height:6px;border-radius:4px;background:var(--chip);overflow:hidden;margin-top:6px}',
    '.bar>i{display:block;height:100%;background:var(--acc);width:0}',
    '#toast{position:fixed;right:18px;bottom:18px;display:flex;flex-direction:column;gap:8px;z-index:20}',
    '.t{padding:10px 14px;border-radius:8px;background:var(--card);border:1px solid var(--line);max-width:440px}',
    '.t.err{border-color:#ff6b6b;color:#ffb3b3}',
    '.hidden{display:none}',
    '.set{display:flex;align-items:center;gap:4px;color:var(--dim);font-size:12px;white-space:nowrap}',
    '.set input{width:62px;padding:4px 6px}',
    '.crumb a{color:var(--acc);cursor:pointer}',
    '.usage{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:12px 14px;font-size:13px}',
    '.usage .row{display:flex;flex-direction:column;gap:8px}',
    '.usage .kv{display:flex;gap:6px;align-items:baseline;flex-wrap:wrap}',
    '.usage .v{font-weight:600;font-size:15px}',
    '.usage .bar{height:6px;border-radius:4px;background:var(--chip);overflow:hidden;margin-top:8px}',
    '.usage .bar>i{display:block;height:100%;background:var(--acc)}',
    '.usage .over{color:#c2410c}',
    '.usage .foot{margin-top:10px;padding-top:8px;border-top:1px solid var(--line);color:var(--dim);font-size:12px}',
    // 多桶用量：每桶一块，两列并排
    '.bgrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}',
    '.bcell{min-width:0;border:1px solid var(--line);border-radius:10px;padding:10px;background:var(--bg)}',
    '.bcell .bname{font-weight:600;margin-bottom:6px;font-size:13px;overflow-wrap:anywhere}',
    '.bcell .row{display:flex;flex-direction:column;gap:4px}',
    '.bcell .kv{gap:4px}',
    '.bcell .v{font-size:13px}',
    '.bcell .muted{font-size:12px;overflow-wrap:anywhere}',
    '</style></head><body>',
    '<header>',
    // 折叠区（桌面 display:contents → 顺序与改造前完全一致）
    '<div class="more" id="moreMenu">',
    '<h1>Backblaze B2 文件管理器</h1>',
    '<span class="muted" id="bucketLabel"></span>',
    '<span class="grow"></span>',
    '<input id="fUser" placeholder="用户名" size="10">',
    '<input id="fPass" type="password" placeholder="密码 / 令牌" size="16">',
    '<button class="ghost" id="btnLogin">鉴权</button>',
    '<button class="ghost" id="btnLogout">退出</button>',
    '<button class="ghost" id="btnRefresh">刷新</button>',
    '<button class="ghost" id="btnCors" title="把一个站点域名加入该桶的 CORS 规则（浏览器直传/跨域下载需要）。默认放行当前站点。">配置CORS</button>',
    '<select id="bucketSel" title="切换到其它桶的管理器"></select>',
    '<label class="set" title="分片大小（MiB）。直传单次 PUT 上限为 5–95，Worker 代理受 MAX_UPLOAD_BYTES 约束；B2 硬上限 100MiB。">分片',
    '<input id="partSize" type="number" min="5" max="95" step="1" value="' + defaultPartMiB + '">MiB</label>',
    '<label class="set" title="分片并发上传数，1–10。越大越快，但更吃带宽/上游限流。">并发',
    '<input id="conc" type="number" min="1" max="10" step="1" value="' + defaultConc + '"></label>',
    '<button class="ghost" id="btnTheme">深色模式</button>',
    '</div>',
    // 移动端常显：更多 / 新建目录 / 上传方式 / 上传
    '<button class="ghost more-toggle" id="btnMore" aria-expanded="false">更多 ▾</button>',
    '<button class="ghost" id="btnMkdir">新建目录</button>',
    '<select id="upMode">',
    '<option value="direct">直传（推荐）</option>',
    '<option value="worker">Worker 代理</option>',
    '</select>',
    '<button id="btnUpload">上传</button>',
    '<input type="file" id="file" multiple class="hidden">',
    '</header>',
    '<main>',
    '<aside class="side"><div id="usage" class="usage"></div></aside>',
    '<section class="content">',
    '<nav class="crumb" id="crumb" style="margin-bottom:12px"></nav>',
    '<table><thead><tr><th>名称</th><th class="c-size">大小</th>',
    '<th class="c-time">修改时间</th><th class="c-act">操作</th></tr></thead>',
    '<tbody id="tb"></tbody></table>',
    '<div id="status" class="muted"></div>',
    '</section>',
    '</main>',
    '<div id="toast"></div>',
    '<script id="cfg" type="application/json">' + configJson + '</script>',
    '<script>' + themeToggleScript() + '</script>',
    '<script>',
    '(function () {',
    'var CFG = JSON.parse(document.getElementById("cfg").textContent);',
    'var API = CFG.apiBase;',
    '/* 请求一律用绝对 URL。若页面是通过 https://user:pass@host/… 打开的（书签里带了凭据），',
    '   相对 URL 会让 fetch 直接抛 “Request cannot be constructed from a URL that includes credentials”，',
    '   用量面板会显示「不可用」、文件列表也一个都列不出来。location.origin 不含凭据，',
    '   同源请求浏览器会自动带上已缓存的 Basic 认证。 */',
    'function absUrl(u) { return /^[a-z][a-z0-9+.-]*:\\/\\//i.test(u) ? u : location.origin + u; }',
    'var PREFIX = "";',
    'var NEXT = "";',
    'var LOADING = false;',
    'var LOADED = 0;',
    'var GEN = 0;',
    'var TOKEN = "";',
    'var SELECT = null;',
    'function el(id) { return document.getElementById(id); }',
    'function esc(s) {',
    '  return String(s).split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;").split(String.fromCharCode(34)).join("&quot;");',
    '}',
    'function size(b) {',
    '  if (!b) return "0 B";',
    '  var u = ["B","KB","MB","GB","TB"], v = b, i = 0;',
    '  while (v >= 1024 && i < u.length - 1) { v = v / 1024; i++; }',
    '  return v.toFixed(i ? 1 : 0) + " " + u[i];',
    '}',
    'function toast(msg, isErr) {',
    '  var d = document.createElement("div");',
    '  d.className = "t" + (isErr ? " err" : "");',
    '  d.textContent = msg;',
    '  el("toast").appendChild(d);',
    '  setTimeout(function () { d.parentNode && d.parentNode.removeChild(d); }, isErr ? 6000 : 2600);',
    '}',
    'function buildHeaders(withBody) {',
    '  var h = { Accept: "application/json" };',
    '  if (withBody) h["Content-Type"] = "application/json";',
    '  if (CFG.publicWrite) return h;',
    '  if (TOKEN) { h.Authorization = "Bearer " + TOKEN; return h; }',
    '  var u = el("fUser").value, p = el("fPass").value;',
    '  if (CFG.hasToken && p) { h.Authorization = "Bearer " + p; return h; }',
    '  if (CFG.hasBasic && (u || p)) { h.Authorization = "Basic " + btoa(u + ":" + p); return h; }',
    '  return h;',
    '}',
    'function call(path, opts) {',
    '  opts = opts || {};',
    '  opts.headers = buildHeaders(!!opts.body);',
    '  opts.credentials = "same-origin";',
    '  return fetch(absUrl(API + path), opts).then(function (r) {',
    '    return r.json().then(function (j) { return { ok: r.ok && j.ok !== false, status: r.status, data: j }; });',
    '  });',
    '}',
    'function q(p) {',
    '  var parts = [];',
    '  for (var k in p) {',
    '    if (p[k] !== undefined && p[k] !== null && p[k] !== "") parts.push(k + "=" + encodeURIComponent(p[k]));',
    '  }',
    '  if (CFG.defaultBucket) parts.push("bucket=" + encodeURIComponent(CFG.defaultBucket));',
    '  return parts.length ? "?" + parts.join("&") : "";',
    '}',
    'function buildRows(data, withUp) {',
    '  var rows = "";',
    '  if (withUp && PREFIX) rows += \'<tr class="dir"><td><a data-act="up">.. 返回上级</a></td><td></td><td></td><td></td></tr>\';',
    '  (data.folders || []).forEach(function (p) {',
    '    var name = p.slice(PREFIX.length);',
    '    if (name.charAt(name.length - 1) === "/") name = name.slice(0, -1);',
    '    rows += "<tr class=\\"dir\\"><td><a data-act=\\"dir\\" data-p=\\"" + esc(p) + "\\">" + esc(name) + "</a></td>"',
    '      + "<td class=\\"muted\\">目录</td><td></td>"',
    '      + "<td class=\\"act\\"><button class=\\"mini\\" data-act=\\"deldir\\" data-k=\\"" + esc(p + ".keep") + "\\">删除</button></td></tr>";',
    '  });',
    '  (data.files || []).filter(function (f) { return f.name !== ".keep"; }).forEach(function (f) {',
    '    var k = esc(PREFIX + f.name);',
    '    rows += "<tr><td>" + esc(f.name) + "</td><td>" + size(f.size) + "</td>"',
    '      + "<td class=\\"muted\\">" + esc(f.lastModified) + "</td>"',
    '      + \'<td class="act">\'',
    '      + \'<button class="mini" data-act="copy" data-k="\' + k + \'">复制</button> \'',
    '      + \'<button class="mini" data-act="dl" data-k="\' + k + \'">下载</button> \'',
    '      + \'<button class="mini" data-act="ren" data-k="\' + k + \'">重命名</button> \'',
    '      + \'<button class="mini" data-act="del" data-k="\' + k + \'">删除</button>\'',
    '      + "</td></tr>";',
    '  });',
    '  return rows;',
    '}',
    'function statusHtml(done) {',
    '  if (LOADING) return \'<span class="spin"></span> 正在加载…\';',
    '  if (!NEXT) return "已加载 " + LOADED + " 项 · 到底了";',
    '  return "已加载 " + LOADED + " 项 · 继续往下滚动加载更多";',
    '}',
    'function paintStatus() { el("status").innerHTML = statusHtml(); }',
    'function paintCrumb() {',
    '  var crumb = [\'<a data-act="dir" data-p="">根目录</a>\'];',
    '  var acc = "";',
    '  PREFIX.split("/").forEach(function (seg) {',
    '    if (!seg) return;',
    '    acc += seg + "/";',
    '    crumb.push(\' <span class="muted">/</span> <a data-act="dir" data-p="\' + esc(acc) + \'">\' + esc(seg) + "</a>");',
    '  });',
    '  el("crumb").innerHTML = crumb.join("");',
    '}',
    '/* 目录内容：瀑布流式加载（滚动到底部自动续接下一页） */',
    'function load(prefix) {',
    '  PREFIX = prefix || "";',
    '  LOADING = true; LOADED = 0; NEXT = ""; GEN++;',
    '  var gen = GEN;',
    '  paintCrumb();',
    '  el("tb").innerHTML = "";',
    '  paintStatus();',
    '  return call("list" + q({ prefix: PREFIX })).then(function (r) {',
    '    if (gen !== GEN) return;',
    '    LOADING = false;',
    '    if (!r.ok) { toast("列举失败: " + (r.data.error || r.status), true); paintStatus(); return; }',
    '    NEXT = r.data.nextToken || "";',
    '    var rows = buildRows(r.data, true);',
    '    LOADED += (r.data.files || []).length + (r.data.folders || []).length;',
    '    el("tb").innerHTML = rows || \'<tr><td colspan="4" class="muted">（空目录）</td></tr>\';',
    '    paintStatus();',
    '  });',
    '}',
    'function loadMore() {',
    '  if (LOADING || !NEXT) return Promise.resolve();',
    '  LOADING = true;',
    '  var gen = GEN;',
    '  var cursor = NEXT;',
    '  paintStatus();',
    '  return call("list" + q({ prefix: PREFIX, cursor: cursor })).then(function (r) {',
    '    if (gen !== GEN) return;',
    '    LOADING = false;',
    '    if (!r.ok) { toast("加载更多失败: " + (r.data.error || r.status), true); paintStatus(); return; }',
    '    NEXT = r.data.nextToken || "";',
    '    el("tb").insertAdjacentHTML("beforeend", buildRows(r.data, false));',
    '    LOADED += (r.data.files || []).length + (r.data.folders || []).length;',
    '    paintStatus();',
    '  });',
    '}',
    'window.addEventListener("scroll", function () {',
    '  if (LOADING || !NEXT) return;',
    '  if (window.innerHeight + window.scrollY >= document.documentElement.scrollHeight - 300) loadMore();',
    '});',
    'function refresh() { load(PREFIX); }',
    'var ERR_DIRECT = "直传失败：浏览器只给笼统错误，请到 DevTools → Network 看真实状态码。常见原因：① 桶未配 CORS（需放行本站与 s3_put）；② 单次 PUT 超过 B2 的 100MiB 上限（超过会自动改走分片，若仍报错请调小 MULTIPART_THRESHOLD）；③ 请求多带了未签名的自定义头（B2 会 400）。";',
    'var ERR_WORKER = "经 Worker 上传失败：网络中断，或单请求超过 MAX_UPLOAD_BYTES（默认 96MB，超过会自动分片）。";',
    'function upMode() { return el("upMode") ? el("upMode").value : "direct"; }',
    'function saveMode() { try { localStorage.setItem("cfb2-upmode", upMode()); } catch (e) {} }',
    '/* 直传：超过阈值 → 并发分片（B2 单次 PUT 实测上限 100MiB）；Worker 代理：超过单请求上限 → 并发分片 */',
    'function uploadFiles(files) {',
    '  for (var i = 0; i < files.length; i++) {',
    '    var f = files[i];',
    '    var key = PREFIX + f.name;',
    '    if (upMode() === "worker") workerUpload(f, key);',
    '    else if (f.size > (CFG.multipartThreshold || 100000000)) mpUpload(f, key);',
    '    else simpleUpload(f, key);',
    '  }',
    '}',
    '/* ---------- 上传调参（输入框 > 服务端默认值；改动记忆在 localStorage） ---------- */',
    'function partCapMB() {',
    '  /* 直传：B2 单次 PUT 上限 100MiB，留 5MiB 余量 → 95；Worker 代理：受 MAX_UPLOAD_BYTES 约束 */',
    '  if (upMode() === "worker") {',
    '    var c = Math.floor(((CFG.maxUploadBytes || 96000000) - 1048576) / 1048576);',
    '    return c < 5 ? 5 : c;',
    '  }',
    '  return 95;',
    '}',
    'function defaultPartMB() { return (CFG.multipartPartSize || 26214400) / 1048576; }',
    'function clampField(id, lo, hi, fallback) {',
    '  var n = el(id);',
    '  var fb = fallback || lo;',
    '  if (!n) return fb;',
    '  var v = parseFloat(n.value);',
    '  if (!isFinite(v) || v <= 0) v = fb;',
    '  v = Math.max(lo, Math.min(hi, Math.round(v)));',
    '  n.value = v;',
    '  return v;',
    '}',
    'function partSizeMB() {',
    '  var cap = partCapMB();',
    '  var n = el("partSize");',
    '  var v = n ? parseFloat(n.value) : NaN;',
    '  if (!isFinite(v) || v <= 0) v = defaultPartMB();',
    '  v = Math.max(5, Math.min(v, cap));',
    '  return Math.round(v * 1048576);',
    '}',
    'function concurrency() {',
    '  var n = el("conc");',
    '  var v = n ? parseInt(n.value, 10) : NaN;',
    '  if (!isFinite(v) || v <= 0) v = CFG.uploadConcurrency || 3;',
    '  return Math.max(1, Math.min(10, v));',
    '}',
    'function saveTuning() {',
    '  try {',
    '    localStorage.setItem("cfb2-tune", JSON.stringify({',
    '      part: el("partSize") ? el("partSize").value : "",',
    '      conc: el("conc") ? el("conc").value : "",',
    '    }));',
    '  } catch (e) {}',
    '}',
    'function syncTuning() {',
    '  var cap = partCapMB();',
    '  var p = clampField("partSize", 5, cap, defaultPartMB());',
    '  var c = clampField("conc", 1, 10, CFG.uploadConcurrency || 3);',
    '  saveTuning();',
    '  return { part: p, conc: c };',
    '}',
    'function directPartSize() { return partSizeMB(); }',
    '/* 失败重试：分片偶发 5xx / 网络抖动时自动重试（最多 3 次，退避 0.8s/1.6s） */',
    'function withRetry(fn, times) {',
    '  var n = times || 3;',
    '  function attempt(i) {',
    '    return fn().catch(function (e) {',
    '      if (i >= n) throw e;',
    '      return new Promise(function (res) { setTimeout(res, 800 * i); })',
    '        .then(function () { return attempt(i + 1); });',
    '    });',
    '  }',
    '  return attempt(1);',
    '}',
    'function workerPartSize() { return partSizeMB(); }',
    '/* 受限并发池：同时最多 limit 个任务，全部完成/失败后 settle */',
    'function runPool(tasks, limit) {',
    '  var idx = 0;',
    '  var firstErr = null;',
    '  function next() {',
    '    if (firstErr || idx >= tasks.length) return Promise.resolve();',
    '    var cur = idx++;',
    '    return tasks[cur]().catch(function (e) { if (!firstErr) firstErr = e; }).then(next);',
    '  }',
    '  var workers = [];',
    '  for (var i = 0; i < Math.max(1, Math.min(limit, tasks.length)); i++) workers.push(next());',
    '  return Promise.all(workers).then(function () { if (firstErr) throw firstErr; });',
    '}',
    'function workerUpload(file, key) {',
    '  var setPct = progressRow(file);',
    '  var ct = file.type || "application/octet-stream";',
    '  if (file.size <= (CFG.maxUploadBytes || 96 * 1000 * 1000)) {',
    '    return putXHR(API + "object" + q({ key: key }), file, ct, setPct, { direct: false })',
    '      .then(function () { setPct(100); toast("上传完成（Worker 代理）: " + key); refresh(); })',
    '      .catch(function (e) { toast("上传失败: " + e.message, true); });',
    '  }',
    '  return workerMultipart(file, key, setPct);',
    '}',
    'function workerMultipart(file, key, setPct) {',
    '  var partSize = workerPartSize();',
    '  var total = Math.ceil(file.size / partSize);',
    '  var ct = file.type || "application/octet-stream";',
    '  var uploadId = "";',
    '  call("multipart/create" + q({ key: key }), { method: "POST", body: JSON.stringify({ contentType: ct }) })',
    '    .then(function (r) {',
    '      if (!r.ok) throw new Error(r.data.error || r.status);',
    '      uploadId = r.data.uploadId;',
    '      var tasks = [];',
    '      var done = 0;',
    '      for (var n = 1; n <= total; n++) {',
    '        tasks.push(workerStep(n, key, uploadId, partSize, file, function () {',
    '          done++; setPct(Math.round(done / total * 100));',
    '        }));',
    '      }',
    '      var conc = concurrency();',
    '      return runPool(tasks, conc).then(function () {',
    '        return call("multipart/complete" + q({ key: key }), {',
    '          method: "POST", body: JSON.stringify({ uploadId: uploadId }),',
    '        });',
    '      });',
    '    })',
    '    .then(function (r) {',
    '      toast(r.ok ? "分片上传完成（Worker 代理，并发 " + concurrency() + "）: " + key',
    '        : "合并失败: " + ((r.data && r.data.error) || "未知"), !r.ok);',
    '      refresh();',
    '    })',
    '    .catch(function (e) {',
    '      if (uploadId) {',
    '        call("multipart/abort" + q({ key: key }), {',
    '          method: "POST", body: JSON.stringify({ uploadId: uploadId }),',
    '        }).catch(function () {});',
    '      }',
    '      toast("分片上传失败（已清理未完成的碎片）: " + e.message, true);',
    '    });',
    '}',
    'function workerStep(n, key, uploadId, partSize, file, done) {',
    '  return function () {',
    '    return withRetry(function () {',
    '      var start = (n - 1) * partSize;',
    '      var chunk = file.slice(start, Math.min(start + partSize, file.size));',
    '      var url = API + "multipart/part" + q({ key: key, uploadId: uploadId, partNumber: n });',
    '      return putXHR(url, chunk, "application/octet-stream", null, { direct: false });',
    '    }, 3).then(done);',
    '  };',
    '}',
    '/* 直传分片：逐片取预签名 URL，浏览器直发 B2（并发 + 失败重试） */',
    'function mpUpload(file, key) {',
    '  var setPct = progressRow(file);',
    '  var partSize = directPartSize();',
    '  var total = Math.ceil(file.size / partSize);',
    '  var ct = file.type || "application/octet-stream";',
    '  var uploadId = "";',
    '  call("multipart/create" + q({ key: key }), { method: "POST", body: JSON.stringify({ contentType: ct }) })',
    '    .then(function (r) {',
    '      if (!r.ok) throw new Error(r.data.error || r.status);',
    '      uploadId = r.data.uploadId;',
    '      var tasks = [];',
    '      var done = 0;',
    '      for (var n = 1; n <= total; n++) {',
    '        tasks.push(directStep(n, key, uploadId, partSize, file, function () {',
    '          done++; setPct(Math.round(done / total * 100));',
    '        }));',
    '      }',
    '      var conc = concurrency();',
    '      return runPool(tasks, conc).then(function () {',
    '        return call("multipart/complete" + q({ key: key }), {',
    '          method: "POST", body: JSON.stringify({ uploadId: uploadId }),',
    '        });',
    '      });',
    '    })',
    '    .then(function (r) {',
    '      toast(r.ok ? "上传完成（直传分片 " + total + " 片，并发 " + concurrency() + "）: " + key',
    '        : "合并失败: " + ((r.data && r.data.error) || "未知"), !r.ok);',
    '      refresh();',
    '    })',
    '    .catch(function (e) {',
    '      if (uploadId) {',
    '        call("multipart/abort" + q({ key: key }), {',
    '          method: "POST", body: JSON.stringify({ uploadId: uploadId }),',
    '        }).catch(function () {});',
    '      }',
    '      toast("上传失败（已清理未完成的碎片）: " + e.message, true);',
    '    });',
    '}',
    'function directStep(n, key, uploadId, partSize, file, done) {',
    '  return function () {',
    '    return withRetry(function () {',
    '      return call("multipart/part" + q({ key: key, uploadId: uploadId, partNumber: n })).then(function (pr) {',
    '        if (!pr.ok) throw new Error(pr.data.error || pr.status);',
    '        var start = (n - 1) * partSize;',
    '        var chunk = file.slice(start, Math.min(start + partSize, file.size));',
    '        return putXHR(pr.data.url, chunk, "application/octet-stream", null, { direct: true });',
    '      });',
    '    }, 3).then(done);',
    '  };',
    '}',
    'function progressRow(file) {',
    '  var tr = document.createElement("tr");',
    '  tr.innerHTML = "<td>" + esc(file.name) + \'<div class="bar"><i></i></div></td>\'',
    '    + "<td>" + size(file.size) + \'</td><td class="muted">上传中</td><td></td>\';',
    '  el("tb").insertBefore(tr, el("tb").firstChild);',
    '  return function (pct) {',
    '    tr.querySelector(".bar > i").style.width = pct + "%";',
    '    if (pct >= 100) tr.children[2].textContent = "处理中";',
    '  };',
    '}',
    'function putXHR(url, blob, ct, setPct, opts) {',
    '  opts = opts || { direct: true };',
    '  return new Promise(function (resolve, reject) {',
    '    var xhr = new XMLHttpRequest();',
    '    xhr.open("PUT", absUrl(url), true);',
    '    xhr.setRequestHeader("Content-Type", ct);',
    '    if (!opts.direct) {',
    '      var h = buildHeaders(false);',
    '      for (var key in h) { if (Object.prototype.hasOwnProperty.call(h, key)) xhr.setRequestHeader(key, h[key]); }',
    '    }',
    '    xhr.upload.onprogress = function (e) {',
    '      if (e.lengthComputable && setPct) setPct(Math.round(e.loaded / e.total * 100));',
    '    };',
    '    xhr.onload = function () {',
    '      if (xhr.status >= 200 && xhr.status < 300) resolve(xhr);',
    '      else reject(new Error("HTTP " + xhr.status + " " + String(xhr.responseText || "").slice(0, 200)));',
    '    };',
    '    xhr.onerror = function () { reject(new Error(opts.direct ? ERR_DIRECT : ERR_WORKER)); };',
    '    xhr.send(blob);',
    '  });',
    '}',
    'function simpleUpload(file, key) {',
    '  var setPct = progressRow(file);',
    '  var ct = file.type || "application/octet-stream";',
    '  call("presign" + q({ key: key, type: "put", ct: ct })).then(function (r) {',
    '    if (!r.ok) { toast("预签名失败: " + (r.data.error || r.status), true); return; }',
    '    return putXHR(r.data.url, file, ct, setPct, { direct: true }).then(function () {',
    '      setPct(100); toast("上传完成（直传）: " + key); refresh();',
    '    });',
    '  }).catch(function (e) { toast("上传失败: " + e.message, true); });',
    '}',
    '/* 绝对地址（跟随当前访问域名，而不是写死某个域名）。',
    '   多桶语义下对象 URL 必须落在挂载点上：公开前缀内的 key 生成 /share/<桶>/<去前缀路径>',
    '   （匿名可访问、可直接分享）；其余生成 /<桶>/<key>（管理员经 Worker 访问）。',
    '   之前用 CFG.basePath 拼接，在全局入口 /__manage 下 basePath 是 "/"，',
    '   会把 /share/110MB.test 这类 URL 的第一段当桶名 → 「未挂载的桶」。 */',
    'function objUrl(key) {',
    '  var enc = key.split("/").map(encodeURIComponent).join("/");',
    '  var pp = (CFG.publicPrefix || "").replace(/\\/+$/, "");',
    '  if (pp && enc.toLowerCase().indexOf(pp.toLowerCase() + "/") === 0) {',
    '    return location.origin + "/share/" + CFG.bucketFixed + "/" + enc.slice(pp.length + 1);',
    '  }',
    '  return location.origin + "/" + CFG.bucketFixed + "/" + enc;',
    '}',
    '/* 复制链接：经 Worker 的可分享地址（与「下载」同一路径，加 ?dl=1 即强制另存） */',
    'function copyText(text) {',
    '  function fallback() { window.prompt("复制这条链接（经 Worker，可直接分享）", text); }',
    '  if (navigator.clipboard && navigator.clipboard.writeText) {',
    '    navigator.clipboard.writeText(text).then(function () { toast("已复制链接: " + text); }, fallback);',
    '    return;',
    '  }',
    '  try {',
    '    var ta = document.createElement("input");',
    '    ta.value = text; document.body.appendChild(ta); ta.select();',
    '    document.execCommand("copy"); document.body.removeChild(ta);',
    '    toast("已复制链接: " + text);',
    '  } catch (e) { fallback(); }',
    '}',
    'function act(a) {',
    '  var k = a.getAttribute("data-k") || "";',
    '  var p = a.getAttribute("data-p") || "";',
    '  if (a.dataset) {',
    '    if (a.dataset.k) k = a.dataset.k;',
    '    if (a.dataset.p) p = a.dataset.p;',
    '  }',
    '  switch (a.getAttribute("data-act")) {',
    '    case "up":',
    '      var segs = PREFIX.replace(/\\/+$/, "").split("/");',
    '      segs.pop();',
    '      load(segs.length ? segs.join("/") + "/" : "");',
    '      break;',
    '    case "dir": load(p); break;',
    '    case "dl":',
    '      window.open(objUrl(k) + "?dl=1", "_blank");',
    '      break;',
    '    case "copy":',
    '      copyText(objUrl(k));',
    '      break;',
    '    case "ren":',
    '      var target = window.prompt("重命名为（输入 其它桶名/路径 可跨桶移动）：", k.split("/").pop());',
    '      if (!target) return;',
    '      var toBucket = CFG.bucketFixed, toKey = PREFIX + target;',
    '      var head = target.split("/")[0].toLowerCase();',
    '      if ((CFG.buckets || []).some(function (b) { return b.name === head; }) && head !== CFG.bucketFixed) {',
    '        toBucket = head;',
    '        toKey = target.slice(head.length + 1);',
    '      }',
    '      call("copy", { method: "POST", body: JSON.stringify({ from: k, to: toKey, toBucket: toBucket, move: true }) })',
    '        .then(function (r) { toast(r.ok ? (r.data.crossBucket ? "已移动到 " + toBucket : "已重命名") : "失败: " + (r.data.error || r.status), !r.ok); refresh(); });',
    '      break;',
    '    case "del":',
    '    case "deldir":',
    '      if (!CFG.enableDelete) { toast("服务端已禁用删除", true); return; }',
    '      if (!window.confirm("确认删除 " + k + " ？")) return;',
    '      call("object" + q({ key: k }), { method: "DELETE" })',
    '        .then(function (r) { toast(r.ok ? "已删除" : "删除失败: " + (r.data.error || r.status), !r.ok); refresh(); });',
    '      break;',
    '    default: break;',
    '  }',
    '}',
    'el("tb").addEventListener("click", function (e) {',
    '  var t = e.target;',
    '  while (t && t !== this && t.tagName !== "BUTTON" && t.tagName !== "A") t = t.parentNode;',
    '  if (!t || t === this) return;',
    '  act(t);',
    '});',
    'el("crumb").addEventListener("click", function (e) {',
    '  if (e.target.tagName === "A") act(e.target);',
    '});',
    'el("btnRefresh").onclick = refresh;',
    '/* 配置CORS：把一个来源写入当前桶的 CORS 规则（B2 原生 API，免费不计次）。',
    '   浏览器直传（presigned PUT）与跨域下载依赖桶级 CORS；默认放行当前站点域名。 */',
    'el("btnCors").onclick = function () {',
    '  var def = (location.origin && location.origin.indexOf("http") === 0) ? location.origin : "https://";',
    '  var o = window.prompt("加入 B2 桶 CORS 的来源（https://域名，可带端口）：", def);',
    '  if (!o) return;',
    '  o = o.replace(/\\/+$/, "");',
    '  call("cors", { method: "POST", body: JSON.stringify({ origin: o }) })',
    '    .then(function (r) {',
    '      var n = r.data && r.data.corsRules ? r.data.corsRules.length : 0;',
    '      toast(r.ok ? "CORS 已更新：已放行 " + o + "（该桶共 " + n + " 条规则）" : "CORS 配置失败: " + ((r.data && r.data.error) || r.status), !r.ok);',
    '    });',
    '};',
    'el("btnUpload").onclick = function () { el("file").click(); };',
    'el("file").onchange = function () { uploadFiles(this.files); this.value = ""; };',
    'el("btnMkdir").onclick = function () {',
    '  var name = window.prompt("目录名：");',
    '  if (!name) return;',
    '  name = name.split("/").join("");',
    '  call("mkdir", { method: "POST", body: JSON.stringify({ prefix: PREFIX + name }) })',
    '    .then(function (r) { toast(r.ok ? "已创建" : "创建失败: " + (r.data.error || r.status), !r.ok); refresh(); });',
    '};',
    'el("btnLogin").onclick = function () {',
    '  SELECT = null;',
    '  var u = el("fUser").value, p = el("fPass").value;',
    '  if (CFG.hasToken) TOKEN = p; else TOKEN = "";',
    '  /* 先换取会话 Cookie：Basic / Bearer 只能挂在 fetch 的请求头上，',
    '     而「下载」是 window.open 普通导航 —— 没有 Cookie 就会被当成匿名，',
    '     非公开前缀的对象会被 308 重定向到 /share/。 */',
    '  fetch(API + "login", {',
    '    method: "POST", credentials: "same-origin",',
    '    headers: { "Content-Type": "application/json" },',
    '    body: JSON.stringify({ token: CFG.hasToken ? p : "", user: u, pass: p })',
    '  }).catch(function () { return null; }).then(function () {',
    '    return call("health");',
    '  }).then(function (r) {',
    '    var okAuth = r.data && r.data.authenticated;',
    '    if (okAuth) { try { sessionStorage.setItem("cfb2-token", TOKEN || ""); } catch (e) {} }',
    '    toast(okAuth ? "鉴权成功" : "鉴权失败", !okAuth);',
    '    refresh();',
    '  });',
    '};',
    'el("btnLogout").onclick = function () {',
    '  TOKEN = "";',
    '  el("fUser").value = "";',
    '  el("fPass").value = "";',
    '  try { sessionStorage.removeItem("cfb2-token"); } catch (e) {}',
    '  fetch(absUrl(API + "logout"), { method: "POST", credentials: "same-origin", headers: { Accept: "application/json" } })',
    '    .catch(function () {})',
    '    .then(function () {',
    '      return fetch(absUrl(API + "health"), {',
    '        credentials: "same-origin",',
    '        headers: { Accept: "application/json", Authorization: "Basic " + btoa("logout:logout") },',
    '      });',
    '    })',
    '    .catch(function () {})',
    '    .then(function () {',
    '      toast("已退出：本地凭据已清除。若浏览器仍自动登录，请关闭标签页/浏览器，或改用 Bearer 令牌模式（退出即时生效）。");',
    '      setTimeout(function () { location.replace(CFG.exitUrl || "/"); }, 900);',
    '    });',
    '};',
    '/* 移动端「更多」折叠：默认收起，点击在 moreMenu 上切换 more-open（桌面该按钮被隐藏，不影响） */',
    'if (el("moreMenu") && el("btnMore")) {',
    '  el("btnMore").onclick = function () {',
    '    var m = el("moreMenu");',
    '    var open = !m.classList.contains("more-open");',
    '    if (open) m.classList.add("more-open"); else m.classList.remove("more-open");',
    '    el("btnMore").textContent = open ? "更多 ▴" : "更多 ▾";',
    '    el("btnMore").setAttribute("aria-expanded", open ? "true" : "false");',
    '  };',
    '}',
    'el("upMode").onchange = function () { saveMode(); syncTuning(); };',
    'try {',
    '  var sm = localStorage.getItem("cfb2-upmode");',
    '  if (sm === "worker" || sm === "direct") el("upMode").value = sm;',
    '} catch (e) {}',
    '/* 调参：输入框优先，其次服务端默认值；改动即时生效并记忆在本机 */',
    'try {',
    '  var tn = JSON.parse(localStorage.getItem("cfb2-tune") || "{}");',
    '  if (tn && tn.part) el("partSize").value = tn.part;',
    '  if (tn && tn.conc) el("conc").value = tn.conc;',
    '} catch (e) {}',
    'el("partSize").onchange = function () { var r = syncTuning(); toast("分片大小已设为 " + r.part + " MiB"); };',
    'el("conc").onchange = function () { var r = syncTuning(); toast("并发数已设为 " + r.conc); };',
    'syncTuning();',
    '/* ---------- B2 用量面板（空间自己遍历算，次数只能自己数） ---------- */',
    'function sizeD(b) {',
    '  /* 用量卡片用十进制单位（与 B2 控制台一致：10 GB = 10,000,000,000 字节） */',
    '  if (!b) return "0 B";',
    '  var u = ["B", "KB", "MB", "GB", "TB"], v = b, i = 0;',
    '  while (v >= 1000 && i < u.length - 1) { v = v / 1000; i++; }',
    '  return v.toFixed(i ? 1 : 0) + " " + u[i];',
    '}',
    'function pct(used, quota) {',
    '  if (!quota) return "";',
    '  var p = used / quota * 100;',
    '  return (p < 1 ? p.toFixed(2) : p.toFixed(1)) + "%";',
    '}',
    'function quotaCell(label, used, quota) {',
    '  var over = quota > 0 && used >= quota;',
    '  return "<span class=\\"kv\\"><span class=\\"muted\\">" + label + "</span>"',
    '    + "<span class=\\"v" + (over ? " over" : "") + "\\">" + used + "</span>"',
    '    + "<span class=\\"muted\\">/ " + (quota || "-") + "</span></span>";',
    '}',
    '/* 用量卡片：全部挂载桶两列并排（按 BUCKET_N 序号排序），每桶只展示',
    '   「桶名 / 已用空间 / 对象数 / Class B / Class C」，计数后端放卡片底部 */',
    'function renderUsage(d) {',
    '  var list = (d && d.buckets) || [];',
    '  var html = "";',
    '  if (!list.length) {',
    '    html += "<div class=\\"row\\"><span>没有已挂载的桶</span></div>";',
    '  } else {',
    '    html += \'<div class="bgrid">\';',
    '    list.forEach(function (b) {',
    '      var s = b.storage || {};',
    '      var quota = b.quotaBytes || 0;',
    '      var cell = "<div class=\\"bcell\\"><div class=\\"bname\\">" + esc(b.label || b.name) + "</div>";',
    '      if (s.ok === false) {',
    '        cell += "<div class=\\"muted\\">空间统计失败：" + esc(s.error || "未知错误") + "</div>";',
    '      } else {',
    '        var used = s.usedBytes || 0;',
    '        cell += "<div class=\\"row\\">"',
    '          + "<span class=\\"kv\\"><span class=\\"muted\\">已用空间:</span><span class=\\"v\\">" + pct(used, quota) + "</span></span>"',
    '          + (quota ? "<span class=\\"muted\\">" + sizeD(used) + " / " + sizeD(quota) + "</span>" : "<span class=\\"muted\\">" + sizeD(used) + "</span>")',
    '          + "<span class=\\"kv\\"><span class=\\"muted\\">对象数</span><span class=\\"v\\">" + (s.objects || 0) + "</span>"',
    '          + (s.complete === false ? "<span class=\\"over\\">（扫描到上限，实际更多）</span>" : "") + "</span>"',
    '          + "</div>";',
    '        if (quota) cell += \'<div class="bar"><i style="width:\' + Math.min(100, used / quota * 100) + \'%"></i></div>\';',
    '      }',
    '      cell += "<div class=\\"row\\" style=\\"margin-top:8px\\">"',
    '        + quotaCell("Class B:", (b.classB || {}).used || 0, (b.classB || {}).quota || 0)',
    '        + quotaCell("Class C:", (b.classC || {}).used || 0, (b.classC || {}).quota || 0)',
    '        + "</div></div>";',
    '      html += cell;',
    '    });',
    '    html += "</div>";',
    '  }',
    '  html += \'<div class="foot"><span>计数后端：\' + esc(d.counterBackendLabel || "-") + "</span></div>";',
    '  el("usage").innerHTML = html;',
    '}',
    'function loadUsage() {',
    '  if (!el("usage")) return;',
    '  el("usage").innerHTML = \'<span class="muted">正在读取用量…</span>\';',
    '  call("usage").then(function (r) {',
    '    if (!r.ok || !r.data || r.data.ok === false) {',
    '      el("usage").innerHTML = \'<span class="muted">用量面板不可用：\' + esc((r.data && r.data.error) || r.status) + "</span>";',
    '      return;',
    '    }',
    '    renderUsage(r.data);',
    '  }).catch(function (e) {',
    '    el("usage").innerHTML = \'<span class="muted">用量面板不可用：\' + esc(e.message) + "</span>";',
    '  });',
    '}',
    'loadUsage();',
    'el("bucketLabel").textContent = "桶: " + CFG.bucketFixed;',
    '/* 桶切换器：跳到目标桶的管理器（多桶挂载） */',
    '(CFG.buckets || []).forEach(function (b) {',
    '  var o = document.createElement("option");',
    '  o.value = b.name;',
    '  o.textContent = b.label;',
    '  if (b.name === CFG.bucket) o.selected = true;',
    '  el("bucketSel").appendChild(o);',
    '});',
    'el("bucketSel").onchange = function () {',
    '  location.href = "/" + el("bucketSel").value + "/__manage";',
    '};',
    'if (CFG.publicWrite) { el("btnLogin").className = "ghost hidden"; el("btnLogout").className = "ghost hidden"; }',
    'try {',
    '  var st = sessionStorage.getItem("cfb2-token");',
    '  if (st && CFG.hasToken) { TOKEN = st; el("fPass").value = st; }',
    '} catch (e) {}',
    'if (CFG.hasToken) { el("fUser").className = "hidden"; el("fPass").placeholder = "Bearer 令牌"; }',
    'load("");',
    '})();',
    '</script>',
    '</body></html>',
  ].join('\n');
}

/* ============================ 9. 主入口与路由 ============================ */

/**
 * 请求入口：准备每请求独立的 cfg 与用量计数器，分发后异步把计数落盘。
 * 计数落盘放在 finally 里，因此出错路径产生的 B2 调用同样会被统计。
 */
